apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: gatekeeper-zone
spec:
  containers:
    - name: hostpath-pod
      image: alpine
      command: ["sleep", "3600"]
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
      volumeMounts:
        - name: host-volume
          mountPath: /host-etc
  volumes:
    - name: host-volume
      hostPath:
        path: /etc
        type: Directory
  restartPolicy: Never
