apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  namespace: audit-zone
spec:
  containers:
    - name: privileged-pod
      image: alpine
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Never