apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: secure-space
subjects:
  - kind: User
    name: secret-manager
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-role
  apiGroup: rbac.authorization.k8s.io
