apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HostPathContainer
metadata:
  name: disallow-privileged
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - gatekeeper-zone