apiVersion: v1
kind: Pod
metadata:
  name: root-user-pod
  namespace: audit-zone
spec:
  containers:
    - name: root-user-pod
      image: alpine
      command: ["sleep", "3600"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
  restartPolicy: Never
